### ISSUE TITLE
Commandline options for compiling directories

### ISSUE THREAD

**Issue by FilipJanitor** [Michael2109/cobalt#489]
Currently both directories and files for compiling are placed together as arguments. 
It might be beneficial to have only files as arguments and directories supplied by commandline options (it seems that this functionality will be used only for testing anyways).
The question is, what letter to use. How about
```
-s <Directory> --source-directory=<directory>
```
Of course, multiple directories could be supplied this way.

**Comment by FilipJanitor** [comment]
So I added the simple implementation and some tests. The list of directories to compile is not yet plugged to the compiler, as the function for compiling directories is in testutils. We will need to figure a way to use it in normal compilation process and maintaining correct common symbol table for both directories and individual files to compile

**Comment by FilipJanitor** [comment]
Any idea how to test this? Preferably automatically, but I havent done it manually either yet.

**Comment by Michael2109** [comment]
For testing this could you run the compiler with this argument before the integration tests start? Currently I'm calling a function called `compileDirectory` in `CompileTestUtil`. Maybe instead of calling that you can just execute the compiler using `withArgs` with something similar to what I was running individually. 
E.g. 
```
withArgs ["-d", outputDir, "-p", classPath, currentDir ++ inputLoc] execute
```
Just by using this to execute all our test classes is enough to confirm it is working correctly.
